### PR TITLE
#168986237 bg(change on userinterface) 

### PR DESCRIPTION
**Pull request by banobepascal**
#### What does this PR do?
Modifies and gives the UI an apealing interface

#### Description of Task to be completed?
- remove hover on articles posted'
- show less words on articles posted
- add navigation navbar on all pages

#### How should this be manually tested?
A user can navigate to the branch(Bg-userInterface-fix) and clone the repo then run the pages in the browser

#### Any background context you want to provide?
Incase a user clones the repo they can compare changes with `https://banobepascal.github.io/teamwork/ui/`

#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/168986237

#### Screenshots 
Inappropiate Articles
before:
admindash

After:
flarticles

###Articles page:
###Before:
home
###After:
after

Inappropiate comments:
###before:
comms

###After:
afterComments

###Settings page:
### After
update

###NEW CHANGES
myp
sett

### CODE REVIEW

**Review by NkFab — COMMENTED** [review]
Can you please remove the search field where it's not needed? Otherwise, everything else looks good.

**Comment by banobepascal** [comment]
> Can you please remove the search field where it's not needed? Otherwise, everything else looks good.

**Comment by banobepascal** [comment]
hey Manzi i have made the changes to the ui

**Comment by NkFab** [comment]
You can go ahead and merge.

**Pull request merged**
